language: php
php:
  - '7.1'
install:
  - composer install --prefer-dist
services:
  - postgresql
cache:
  directories:
    - vendor
before_script:
  - psql -c 'create database phector_test;' -U postgres
after_success:
  - travis_retry php vendor/bin/php-coveralls
